apiVersion: apps/v1
kind: Deployment
metadata:
  name: lestvica-transparentnosti-deployment
  labels:
    app: lestvica-transparentnosti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lestvica-transparentnosti
  template:
    metadata:
      labels:
        app: lestvica-transparentnosti
    spec:
      initContainers:
        - name: collectstatic
          image: lestvica-transparentnosti
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: api.settings
          envFrom:
            - secretRef:
                name: lestvica-transparentnosti-api-secrets
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 200m
        - name: migrate
          image: lestvica-transparentnosti
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: api.settings
          envFrom:
            - secretRef:
                name: lestvica-transparentnosti-api-secrets
          resources:
            requests:
              memory: 1Gi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 200m
      containers:
        - name: lestvica-transparentnosti
          image: lestvica-transparentnosti
          command:
            - gunicorn
            - lestvica-transparentnosti_project.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "120"
          ports:
            - containerPort: 8000
          envFrom:
              - secretRef:
                  name: lestvica-transparentnosti-api-secrets
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: api.settings
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 500m
