apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lestvica-transparentnosti
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: lestvica-transparentnosti
    newName: rg.fr-par.scw.cloud/djnd/lestvica-transparentnosti
    newTag: '80aff4232bf8583cbe5e88b4244f9a43d474a5c7'
