apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lestvica-transparentnosti
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
images:
  - name: lestvica-transparentnosti
    newName: rg.fr-par.scw.cloud/djnd/lestvica-transparentnosti
    newTag: '57e3f68bbc61b4a0a4aa0cbaab24928b8b8dab64'
  - name: lestvica-transparentnosti-front
    newName: rg.fr-par.scw.cloud/djnd/lestvica-transparentnosti-front
    newTag: '57e3f68bbc61b4a0a4aa0cbaab24928b8b8dab64'
