apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lestvica-transparentnosti
resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
images:
  - name: lestvica-transparentnosti
    newName: rg.fr-par.scw.cloud/djnd/lestvica-transparentnosti
    newTag: 'c11ade63a9e1bfb23c70d58a51ff6456a1f1375e'
  - name: lestvica-transparentnosti-front
    newName: rg.fr-par.scw.cloud/djnd/lestvica-transparentnosti-front
    newTag: 'c11ade63a9e1bfb23c70d58a51ff6456a1f1375e'
