apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lestvica-transparentnosti
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: lestvica-transparentnosti
    newName: rg.fr-par.scw.cloud/djnd/lestvica-transparentnosti
    newTag: '39237623e48701c41e1c87d91e1a786c0ce43f7d'
