version: '3'

services:
  api:
    build: ./api
    ports:
      - 8000:8000
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_DEBUG: "yes"
      DJANGO_SETTINGS_MODULE: api.settings
      DJANGO_SECRET_KEY: make-me-secret
    volumes:
      - ./api:/app
