# Generated by Django 3.2.6 on 2021-08-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0002_group_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('original_text', models.TextField(editable=False)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lestvica.municipality')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lestvica.question')),
            ],
        ),
    ]
