# Generated by Django 3.2.6 on 2021-08-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(),
        ),
    ]
