# Generated by Django 3.2.6 on 2021-08-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0005_auto_20210824_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='category',
            field=models.TextField(choices=[('population', 'population'), ('budget', 'budget'), ('score', 'score')]),
        ),
    ]
