# Generated by Django 3.2.6 on 2021-08-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0006_alter_bucket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lestvica.group')),
            ],
        ),
    ]
