# Generated by Django 3.2.6 on 2021-08-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0007_groupbucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='name',
        ),
        migrations.AddField(
            model_name='bucket',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
