# Generated by Django 3.2.6 on 2021-08-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0008_auto_20210826_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
