# Generated by Django 3.2.6 on 2021-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0009_municipality_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
