# Generated by Django 3.2.7 on 2021-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0010_municipality_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
    ]
