# Generated by Django 3.2.7 on 2021-09-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lestvica', '0011_question_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.FloatField(default=1),
        ),
    ]
